### ISSUE TITLE
docker是什么，有什么用

### ISSUE THREAD

**Issue by zanpy3** [Mokwang/nCoVpush#2]
请问，第二步骤中的docker是什么，有什么用

**Comment by Mokwang** [comment]
第二步骤是让程序在docker中运行，这样能保证程序在server上持续运行下去，不会出现推出ssh时程序终止运行的情况。[docker介绍与使用教程](https://www.runoob.com/docker/docker-tutorial.html)
也可以选择不用docker，直接在有Python3的环境的机器上运行，步骤如下：
> 1. 机器安装python3
> 2. 安装requests模块`pip install requests`或`pip3 install requests`
> 3. clone 代码到机器，在代码文件目录下建立文件sckey_file，用来保存从server酱获取的sckey
> 4. 运行程序`python3 getdata.py`
